"""Create food_menu table

Revision ID: 404510c04753
Revises: 9cae1f60c8f6
Create Date: 2024-06-19 12:55:20.044122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404510c04753'
down_revision = '9cae1f60c8f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('menu_name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('instructions', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_menu')
    # ### end Alembic commands ###
